name: terminabot_ii
description: Flutter project for self-practice and self-satisfaction

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0 #for icon changes

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.0

flutter_icons:
  image_path_android: "assets/icon/terminate.png"
  image_path_ios: "assets/icon/terminate.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/terminate.png"
  windows:
    generate: true
    image_path: "assets/icon/terminate.png"
  macos:
    generate: true
    image_path: "assets/icon/terminate.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
